fix: InputStageAvailable is a property
`IsInputStageAvailable` is a property that returns a bool, however it is called as a function in 

setting the `InputStage` property raises:
```
TypeError: 'bool' object is not callable
```

this fix accesses it as a property instead of as a function